version: 2
jobs:
  build:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Build image
          command: docker-compose build
      - run:
          name: Save built image
          command: docker save -o ~/image.last.tar.gz echo
      - save_cache:
          key: docker-image-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/image.last.tar.gz
  deploy:
    machine: true
    working_directory: ~/app
    steps:
      - restore_cache:
          key: docker-image-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run docker cloud client
          command: docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST dockercloud/client -u $DOCKER_USER -p $DOCKER_PASS tsamsiyu/test
workflows:
  version: 2
  full:
    jobs:
      - build
      - deploy:
          requires:
            - build
